services:
  backend:
    build: 
      context: backend/
      target: development
    container_name: backend_dev
    ports:
      - "${BACKEND_PORT}:3000"
    networks:
      - backend_dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./backend:/home/node
      - /home/node/node_modules
 
  db:
    image: postgres:18
    container_name: db_dev
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - backend_dev

volumes:
  postgres_dev_data:

networks:
  backend_dev:
    driver: bridge
