services:
  backend:
    build: 
      context: backend/
      target: production
    container_name: backend
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:3000"
    networks:
      - backend
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
  
  db:
    image: postgres:18
    container_name: db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}    
    volumes:
      - postgres_data:/var/lib/postgresql_dev/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
